# CICD - Price Front
---
unit_test:
  docker:
    image: "node:7.10-wheezy"
    workdir: "/price-front"

  report: "junit.xml"

  commands:
    - "npm install"
    - "npm run test:ci"

build:
  docker:
    image: "node:7.10-wheezy"
    workdir: "/price-front"

  commands:
    - "npm install"
    - "npm run build"
    revision_file_path: "/build/rev.txt"
