export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const FETCH_UPLOAD = 'FETCH_UPLOAD';
export const FETCH_SPECIAL_PRICE_SEARCH = 'FETCH_SPECIAL_PRICE_SEARCH';